[uwsgi]

http = 0.0.0.0:8000

module = backend.wsgi:application

need-app = true

master = true

processes = 4

max-requests = 1000
max-requests-delta = 100

harakiri = 60

die-on-term = true

vacuum = true

enable-threads = true

lazy-apps = true

single-interpreter = true

buffer-size = 32768

thunder-lock = true

memory-report = true